language: node_js
node_js:
  - 11.6.0

cache: npm

services:
  - docker

before_install:
  - docker build -t jitrogith/awsec2-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true jitrogith/awsec2-docker npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2" 
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-084943921102"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
