language: node_js
node_js:
  - 11.6.0

services:
  - docker

before_install:
  - docker build -t jitrogith/awsec2-docker -f Dockerfile.dev .

script:
  - docker run jitrogith/awsec2-docker npm run test -- --coverage